### ISSUE TITLE
编译到openresty里报错

### ISSUE THREAD

**Issue by zhongchongan** [api7/apisix-nginx-module#17]
![image](https://user-images.githubusercontent.com/87646634/126150305-7e91931e-b93d-4b82-a68e-b1b60705d99c.png)

**Comment by spacewander** [comment]
You should build it with OpenSSL 1.1.1.
Better to build like https://github.com/api7/apisix-build-tools#example (in a docker with OpenResty-OpenSSL 1.1.1 set up correctly.
