### ISSUE TITLE
add real-ip plugin failed， logs get error 

### ISSUE THREAD

**Issue by ccwall3** [api7/apisix-nginx-module#33]
2022/01/04 18:05:17 [error] 24003#24003: *79260034 [lua] real-ip.lua:103: phase_func(): need to build APISIX-OpenResty to support setting real ip, client: 10.8.171.254, server: _, request: "POST /backend-auth/dept/query HTTP/1.1", host: "devapi.meomeopet.com", referrer: "http://localhost:8000/auth/department"
2022/01/04 18:05:17 [warn] 24003#24003: *79260034 [lua] plugin.lua:658: run_plugin(): real-ip exits with http status code 501, client: 10.8.171.254, server: _, request: "POST /backend-auth/dept/query HTTP/1.1", host: "devapi.meomeopet.com", referrer: "http://localhost:8000/auth/department"
2022/01/04 18:05:17 [error] 24003#24003: *79260035 [lua] real-ip.lua:103: phase_func(): need to build APISIX-OpenResty to support setting real ip, client: 10.8.171.254, server: _, request: "POST /backend-auth/dept/queryUser HTTP/1.1", host: "devapi.meomeopet.com", referrer: "http://localhost:8000/auth/department"

how to use  apisix-nginx-module  to  repair this problem

**Comment by membphis** [comment]
@ccwall3 https://github.com/api7/apisix-build-tools

you can take a look at this repo.
