### ISSUE TITLE
ngx_last_reopen_msec is at risk of overflow.

### ISSUE THREAD

**Issue by zfs123** [api7/apisix-nginx-module#64]
ngx_last_reopen_msec = tp->sec * 1000 + tp->msec;

On 32-bit machines，tp->sec is time_t, may tp->sec * 1000 overflow ?

**Comment by spacewander** [comment]
apisix-base and its Nginx modules are designed to run on x64 and arm64 only.
But pull request is welcome if the change can make it run on 32bit platform.

**Comment by zfs123** [comment]
thx.
